name: PR checks

on:
  pull_request:
  workflow_dispatch:

env:
  # Enable rspec color output
  SPEC_OPTS: --force-color

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install PDK
      run: |
        set -ex
        distro=$(lsb_release -cs)
        curl -sSO  "https://apt.puppet.com/puppet-tools-release-${distro}.deb"
        sudo dpkg -i "puppet-tools-release-${distro}.deb"
        rm "puppet-tools-release-${distro}.deb"
        sudo apt-get update -qq
        sudo apt-get install -qy pdk
    - run: pdk validate

    - name: Confirm REFERENCE.md is up-to-date
      run: |
        pdk bundle exec puppet strings generate --format markdown
        git add .
        git diff --staged --color --exit-code

    - name: Confirm PDK update does nothing
      run: |
        pdk update --force
        git add .
        git diff --staged  --color --exit-code

  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
    - run: bundle exec rake spec

  test-acceptance:
    name: Acceptance tests
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            puppet: 7
          - os: ubuntu-latest
            puppet: 8
          - os: macos-latest
            puppet: 8
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Puppet
      run: |
        set -ex
        case ${{ matrix.os }} in
          macos*)
            brew install --cask puppetlabs/puppet/puppet-agent-${{ matrix.puppet }}
            brew install --cask puppetlabs/puppet/pdk
          ;;
          ubuntu*)
            distro=$(lsb_release -cs)
            deb_name="puppet${{ matrix.puppet }}-release-${distro}.deb"
            curl -sSO  "https://apt.puppet.com/${deb_name}"
            sudo dpkg -i "$deb_name"
            rm "$deb_name"
            sudo apt-get update -qq
            sudo apt-get install -qy puppet-agent pdk
          ;;
          *)
            echo ::error::Unsupported platform
            exit 1
          ;;
        esac
    - name: Install PDK dependencies
      run: sudo -E /opt/puppetlabs/pdk/bin/pdk bundle install
    - name: Run acceptance tests
      run: sudo -E /opt/puppetlabs/pdk/bin/pdk bundle exec rake litmus:acceptance:localhost
